export const REGISTER_REPRESENTATIVE_INITIATED = 'REGISTER_REPRESENTATIVE_INITIATED'
export const REGISTER_REPRESENTATIVE_SUCCESS = 'REGISTER_REPRESENTATIVE_SUCCESS'
export const REGISTER_REPRESENTATIVE_FAILURE = 'REGISTER_REPRESENTATIVE_FAILURE'
export const RESET_REPRESENTATIVE_STATE = 'RESET_REPRESENTATIVE_STATE'

export const FETCH_REPRESENTATIVE_INITIATED = 'FETCH_REPRESENTATIVE_INITIATED'
export const FETCH_REPRESENTATIVE_SUCCESS = 'FETCH_REPRESENTATIVE_SUCCESS'
export const FETCH_REPRESENTATIVE_FAILED = 'FETCH_REPRESENTATIVE_FAILED'

export const UPDATE_REPRESENTATIVE_INITIATED = 'UPDATE_REPRESENTATIVE_INITIATED'
export const UPDATE_REPRESENTATIVE_SUCCESS = 'UPDATE_REPRESENTATIVE_SUCCESS'
export const UPDATE_REPRESENTATIVE_FAILED = 'UPDATE_REPRESENTATIVE_FAILED'
export const RESET_UPDATE_REPRESENTATIVE_STATE = 'RESET_UPDATE_REPRESENTATIVE_STATE'

export const PAGE_CHANGE = 'PAGE_CHANGE'
export const SELECT_CHANGE = 'SELECT_CHANGE'

export const FETCH_REPRESENTATIVES_LIST_INITIATED = 'FETCH_REPRESENTATIVES_LIST_INITIATED'
export const FETCH_REPRESENTATIVES_LIST_SUCCESS = 'FETCH_REPRESENTATIVES_LIST_SUCCESS'
export const FETCH_REPRESENTATIVES_LIST_FAILED = 'FETCH_REPRESENTATIVES_LIST_FAILED'
export const RESET_REPRESENTATIVES_LIST = 'RESET_REPRESENTATIVES_LIST_LIST'
