export const ADD_CUSTOM_ATTRIBUTE_INITIATED = 'ADD_CUSTOM_ATTRIBUTE_INITIATED'
export const ADD_CUSTOM_ATTRIBUTE_SUCCESS = 'ADD_CUSTOM_ATTRIBUTE_SUCCESS'
export const ADD_CUSTOM_ATTRIBUTE_FAILURE = 'ADD_CUSTOM_ATTRIBUTE_FAILURE'
export const RESET_ADD_CUSTOM_ATTRIBUTE = 'RESET_ADD_CUSTOM_ATTRIBUTE'

export const GET_CUSTOM_ATTRIBUTE_BY_ID_INITIATED = 'GET_CUSTOM_ATTRIBUTE_BY_ID_INITIATED'
export const GET_CUSTOM_ATTRIBUTE_BY_ID_SUCCESS = 'GET_CUSTOM_ATTRIBUTE_BY_ID_SUCCESS'
export const GET_CUSTOM_ATTRIBUTE_BY_ID_FAILURE = 'GET_CUSTOM_ATTRIBUTE_BY_ID_FAILURE'
export const RESET_GET_CUSTOM_ATTRIBUTE_BY_ID = 'RESET_GET_CUSTOM_ATTRIBUTE_BY_ID'

export const UPDATE_CUSTOM_ATTRIBUTE_INITIATED = 'UPDATE_CUSTOM_ATTRIBUTE_INITIATED'
export const UPDATE_CUSTOM_ATTRIBUTE_SUCCESS = 'UPDATE_CUSTOM_ATTRIBUTE_SUCCESS'
export const UPDATE_CUSTOM_ATTRIBUTE_FAILURE = 'UPDATE_CUSTOM_ATTRIBUTE_FAILURE'
export const RESET_UPDATE_CUSTOM_ATTRIBUTE = 'RESET_UPDATE_CUSTOM_ATTRIBUTE'

export const DELETE_CUSTOM_ATTRIBUTE_INITIATED = 'DELETE_CUSTOM_ATTRIBUTE_INITIATED'
export const DELETE_CUSTOM_ATTRIBUTE_SUCCESS = 'DELETE_CUSTOM_ATTRIBUTE_SUCCESS'
export const DELETE_CUSTOM_ATTRIBUTE_FAILURE = 'DELETE_CUSTOM_ATTRIBUTE_FAILURE'

export const LIST_CUSTOM_ATTRIBUTES_INITIATED = 'LIST_CUSTOM_ATTRIBUTES_INITIATED'
export const LIST_CUSTOM_ATTRIBUTES_SUCCESS = 'LIST_CUSTOM_ATTRIBUTES_SUCCESS'
export const LIST_CUSTOM_ATTRIBUTES_FAILURE = 'LIST_CUSTOM_ATTRIBUTES_FAILURE'
export const RESET_LIST_CUSTOM_ATTRIBUTES = 'RESET_LIST_CUSTOM_ATTRIBUTES'

export const PAGE_CHANGE = 'PAGE_CHANGE'
export const PAGE_RESET = 'PAGE_RESET'
export const SELECT_CHANGE = 'SELECT_CHANGE'
