export const FETCH_CONTACT_INITIATED = 'FETCH_CONTACT_INITIATED'
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const FETCH_CONTACT_FAILED = 'FETCH_CONTACT_FAILED'

export const PAGE_CHANGE = 'PAGE_CHANGE'
export const SELECT_CHANGE = 'SELECT_CHANGE'

export const FETCH_CONTACTS_LIST_INITIATED = 'FETCH_CONTACTS_LIST_INITIATED'
export const FETCH_CONTACTS_LIST_SUCCESS = 'FETCH_CONTACTS_LIST_SUCCESS'
export const FETCH_CONTACTS_LIST_FAILED = 'FETCH_CONTACTS_LIST_FAILED'
export const RESET_CONTACTS_LIST = 'RESET_CONTACTS_LIST_LIST'

export const DELETE_CONTACT_INITIATED = 'DELETE_CONTACT_INITIATED'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED'

export const UPDATE_CONTACT_INITIATED = 'UPDATE_CONTACT_INITIATED'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED'
export const RESET_UPDATE_CONTACT_STATE = 'RESET_UPDATE_CONTACT_STATE'

export const EXPORT_CSV_CONTACTS_INITIATED = 'FETCH_CSV_CONTACTS_INITIATED'
export const EXPORT_CSV_CONTACTS_SUCCESS = 'FETCH_CSV_CONTACTS_SUCCESS'
export const EXPORT_CSV_CONTACTS_FAILED = 'FETCH_CSV_CONTACTS_FAILED'
export const RESET_EXPORT = 'RESET_EXPORT'
