export const REGISTER_EVENT_INITIATED = 'REGISTER_EVENT_INITIATED'
export const REGISTER_EVENT_SUCCESS = 'REGISTER_EVENT_SUCCESS'
export const REGISTER_EVENT_FAILURE = 'REGISTER_EVENT_FAILURE'
export const RESET_EVENT_STATE = 'RESET_EVENT_STATE'

export const FETCH_EVENT_INITIATED = 'FETCH_EVENT_INITIATED'
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS'
export const FETCH_EVENT_FAILED = 'FETCH_EVENT_FAILED'

export const UPDATE_EVENT_INITIATED = 'UPDATE_EVENT_INITIATED'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_FAILED = 'UPDATE_EVENT_FAILED'
export const RESET_UPDATE_EVENT_STATE = 'RESET_UPDATE_EVENT_STATE'

export const PAGE_CHANGE = 'PAGE_CHANGE'
export const SELECT_CHANGE = 'SELECT_CHANGE'

export const FETCH_EVENTS_LIST_INITIATED = 'FETCH_EVENTS_LIST_INITIATED'
export const FETCH_EVENTS_LIST_SUCCESS = 'FETCH_EVENTS_LIST_SUCCESS'
export const FETCH_EVENTS_LIST_FAILED = 'FETCH_EVENTS_LIST_FAILED'
export const RESET_EVENTS_LIST = 'RESET_EVENTS_LIST_LIST'

export const DELETE_EVENT_INITIATED = 'DELETE_EVENT_INITIATED'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_FAILED = 'DELETE_EVENT_FAILED'
